# Generated by Django 4.1.3 on 2022-12-01 15:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='buyer_wishes',
            field=tinymce.models.HTMLField(blank=True, help_text='Please, write all your wishes here', max_length=10000, null=True, verbose_name='buyer wishes'),
        ),
    ]
