# Generated by Django 4.1.3 on 2022-12-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0002_armorreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armororder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_armors', to='forge.buyer', verbose_name='buyer'),
        ),
    ]
